package practica;
// Generated 13-ene-2020 19:58:32 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Faccion generated by hbm2java
 */
public class Faccion implements java.io.Serializable {

	private int faccionId;
	private String nombreFaccion;
	private String lore;
	private Set personajes = new HashSet(0);

	public Faccion() {
	}

	public Faccion(int faccionId) {
		this.faccionId = faccionId;
	}

	public Faccion(int faccionId, String nombreFaccion, String lore, Set personajes) {
		this.faccionId = faccionId;
		this.nombreFaccion = nombreFaccion;
		this.lore = lore;
		this.personajes = personajes;
	}

	public int getFaccionId() {
		return this.faccionId;
	}

	public void setFaccionId(int faccionId) {
		this.faccionId = faccionId;
	}

	public String getNombreFaccion() {
		return this.nombreFaccion;
	}

	public void setNombreFaccion(String nombreFaccion) {
		this.nombreFaccion = nombreFaccion;
	}

	public String getLore() {
		return this.lore;
	}

	public void setLore(String lore) {
		this.lore = lore;
	}

	public Set getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set personajes) {
		this.personajes = personajes;
	}

}
